# Generated by Django 4.2.5 on 2023-09-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceTech', '0002_alter_spacetech_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacetech',
            old_name='des',
            new_name='description',
        ),
    ]
