# Generated by Django 4.2.5 on 2023-10-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceTech', '0003_rename_des_spacetech_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacetech',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
